###
GET http://localhost:3000/api
Content-Type: application/json

### For all users to login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username": "anandu",
    "email": "mail@anandu.net",
    "password": "password"
}
> {% client.global.set("token", response.body.access_token); %}

### for student to update his/her details, FA name etc
POST http://localhost:3000/api/users/update
### for student -> his application, for FA, Academic -> the applicatons under them
GET http://localhost:3000/applicatoin
### for application owner to create
POST http://localhost:3000/api/application/create
### for application owner to update [ should revert verification status ]
POST http://localhost:3000/api/application/update
### to verify, reject, waitlist
POST http://localhost:3000/api/application/status/update
### for library, hostel section to uplaod dues
POST http://localhost:3000/api/due/upload







